import os,tempfile,streamlit as st
from qdrant_utils import get_qdrant_client
from pptx import Presentation
import openai

openai.api_key=os.getenv('OPENAI_API_KEY')
- client,COL = get_qdrant_client(
-     host=os.getenv('QDRANT_URL'),
-     port=int(os.getenv('QDRANT_PORT', 6333)),
-     api_key=os.getenv('QDRANT_API_KEY')
- )
+ client, COLLECTION = get_qdrant_client(
+     host=os.getenv('QDRANT_HOST', 'localhost'),
+     port=int(os.getenv('QDRANT_PORT', 6333)),
+     api_key=os.getenv('QDRANT_API_KEY')
+ )


st.title('📈 TrendScout Dashboard')

def fetch_top_niches(k=10):
    res=client.scroll(collection_name=COL,with_payload=True,limit=200)
    items=[{'term':p.payload.get('term'),'momentum':p.payload.get('momentum'),'cluster':p.payload.get('cluster')} for p in res]
    return sorted(items,key=lambda x:x['momentum'],reverse=True)[:k]

k=st.number_input('Top K Niches',1,20,10)
n=fetch_top_niches(k)
st.subheader(f'Top {k} Niches')
for it in n: st.write(f"**{it['term']}** (Momentum: {it['momentum']:.2f})")

if st.button('Generate Business Plan Deck'):
    prs=Presentation()
    slide=prs.slides.add_slide(prs.slide_layouts[0])
    slide.shapes.title.text='TrendScout Business Plan'
    slide.placeholders[1].text='Generated by Adaptixx.ai'
    for it in n:
        prompt=f"""Create business plan bullet points for niche '{it['term']}' following outlined sections: 1. Market Problem ... 7. Financials. Provide 2-3 bullets each."""
        resp=openai.ChatCompletion.create(model='gpt-4o-mini',messages=[{'role':'system','content':'You are a concise business plan generator.'},{'role':'user','content':prompt}])
        text=resp.choices[0].message.content
        sl=prs.slides.add_slide(prs.slide_layouts[1]); sl.shapes.title.text=it['term']; bm=sl.shapes.placeholders[1].text_frame
        for ln in text.split('\n'):
            if ln.strip(): p=bm.add_paragraph(); p.text=ln.strip(); p.level=1
    tmp=tempfile.NamedTemporaryFile(delete=False,suffix='.pptx'); prs.save(tmp.name)
    st.success('Plan generated!'); st.markdown(f"[Download PPTX]({tmp.name})")
